version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grimoire-server
    environment:
      - ETH_URL=${ETH_URL}
      - ETH_ADDR=${ETH_ADDR}
      - PRIVATE_KEY=${PRIVATE_KEY}
    links:
      - postgres
    ports:
      - 8080:8080
    entrypoint: './main'
    
  postgres:
    image: postgres:15
    container_name: gin-postgres
    environment:
      - POSTGRES_USER=demystif
      - POSTGRES_PASSWORD=gppw2023
      - POSTGRES_DB=gin-postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: gin-postgres
